services:
  db:
    image: mysql:8.0
    container_name: mysqldb
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: David@06
      MYSQL_DATABASE: appdb
    ports:
      - "3307:3306"
    networks:
      - fullstack-net
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 5s
      timeout: 5s
      retries: 10

  backend:
    build: ./springapp
    container_name: springapp
    ports:
      - "8080:8080"
    depends_on:
      db:
        condition: service_healthy
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/appdb
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: David@06
    networks:
      - fullstack-net

  frontend:
    build: ./reactapp
    container_name: reactapp
    ports:
      - "3000:80"
    depends_on:
      - backend
    networks:
      - fullstack-net

networks:
  fullstack-net:
    driver: bridge
