package com.examly.springapp.model.ai;

public enum AnalysisType {
    TOURNAMENT_PROCESSING,
    MATCH_ANALYSIS,
    PLAYER_PERFORMANCE,
    TEAM_TACTICS,
    PREDICTION_MODEL,
    ANOMALY_DETECTION,
    WORKFLOW_OPTIMIZATION,
    SCHEDULING_OPTIMIZATION,
    COMPLIANCE_CHECK,
    RISK_ASSESSMENT
}
