package com.examly.springapp.model.ai;

public enum AnomalyType {
    PERFORMANCE_ANOMALY,
    BEHAVIORAL_ANOMALY,
    DATA_INTEGRITY_ANOMALY,
    SECURITY_ANOMALY,
    SYSTEM_ANOMALY,
    FINANCIAL_ANOMALY,
    COMPLIANCE_ANOMALY,
    SCHEDULING_ANOMALY,
    USER_ACTIVITY_ANOMALY,
    NETWORK_ANOMALY,
    DATABASE_ANOMALY,
    API_ANOMALY,
    RESOURCE_ANOMALY,
    CONFIGURATION_ANOMALY,
    DEPLOYMENT_ANOMALY
}
