package com.examly.springapp.model.ai;

public enum ModelType {
    PREDICTION_MODEL,
    CLASSIFICATION_MODEL,
    REGRESSION_MODEL,
    CLUSTERING_MODEL,
    ANOMALY_DETECTION_MODEL,
    RECOMMENDATION_MODEL,
    NLP_MODEL,
    TIME_SERIES_MODEL,
    DEEP_LEARNING_MODEL,
    ENSEMBLE_MODEL
}
