package com.examly.springapp.model.ai;

public enum WorkflowType {
    TOURNAMENT_PROCESSING,
    MATCH_SCHEDULING,
    PLAYER_REGISTRATION,
    TEAM_VERIFICATION,
    NOTIFICATION_DISPATCH,
    DATA_VALIDATION,
    COMPLIANCE_CHECK,
    REPORT_GENERATION,
    ANOMALY_RESPONSE,
    SYSTEM_MAINTENANCE,
    BACKUP_PROCESS,
    SECURITY_SCAN,
    PERFORMANCE_MONITORING,
    USER_ONBOARDING,
    DOCUMENT_PROCESSING
}
