package com.examly.springapp.service;

import com.examly.springapp.model.Ticket;
import com.examly.springapp.repository.TicketRepository;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Service;

import java.util.List;

@Service
public class TicketService {

    @Autowired
    private TicketRepository ticketRepository;

    public Ticket bookTicket(Ticket ticket, Long userId) {
        ticket.setUserId(userId);
        // Ticket ID will be auto-generated by the database (IDENTITY strategy)
        return ticketRepository.save(ticket);
    }

    public List<Ticket> getMyTickets(Long userId) {
        return ticketRepository.findByUserId(userId);
    }
}