spring.jpa.generate-ddl=true
spring.jpa.show-sql=true
spring.datasource.url=${DATABASE_URL:jdbc:mysql://localhost:3306/appdb?createDatabaseIfNotExist=true}
spring.datasource.username=${DATABASE_USERNAME:root}
spring.datasource.password=${DATABASE_PASSWORD:examly}
spring.jpa.hibernate.ddl-auto=update
server.port=${PORT:8080}
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect
